package uk.gov.justice.generation.pojo.core;

import java.nio.file.Path;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Repository of resources used in the generation of java pojo source files
 * 
 */
public class GenerationContext {

    private final Path outputDirectoryPath;
    private final String packageName;
    private final String sourceFilename;
    private final List<String> ignoredClassNames;

    public GenerationContext(
            final Path outputDirectoryPath,
            final String packageName,
            final String sourceFilename,
            final List<String> ignoredClassNames) {
        this.outputDirectoryPath = outputDirectoryPath;
        this.packageName = packageName;
        this.sourceFilename = sourceFilename;
        this.ignoredClassNames = ignoredClassNames;
    }

    /**
     * Gets the output directory where the generated *.java source files are written.
     *
     * @return The path to the source output directory
     */
    public Path getOutputDirectoryPath() {
        return outputDirectoryPath;
    }

    /**
     * Gets the package name that the *.java POJOs will be generated with
     *
     * @return The java package of the generated POJOss
     */
    public String getPackageName() {
        return packageName;
    }

    /**
     * Gets the name of the JSON schema file that is being used for the generation of
     * the java POJOs
     *
     * @return The name of the JSON schema file
     */
    public String getSourceFilename() {
        return sourceFilename;
    }

    /**
     * Gets a logger. Will display output as part of the Maven build
     *
     * @param clazz The class of the object outputting the logging
     * @return The application's logger
     */
    public Logger getLoggerFor(final Class<?> clazz) {
        return LoggerFactory.getLogger(clazz);
    }


    /**
     * Gets the list of ignored POJOs. This is to allow the user to write their own java POJOs
     * in which case the generator will ignore these files and not generate it's own version
     *
     * @return A list of 'Hard Coded' java pojos that should not be generated by the application
     */
    public List<String> getIgnoredClassNames() {
        return ignoredClassNames;
    }
}
