dist: trusty
sudo: false
language: java
jdk:
  - oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh -DexcludeGroupIds=uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script.sh coveralls:report"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    secure: Ml7PRIH3nVt84qjik/jQ1pjJnXLPipvuUw5KHpMDyZrkDRkNtvnoeWep/SuBWGiGgwKBcL8Pi6QB4jTH8pYVuoUrqQ4Ah4cBQihYTAezMIw+xGulF0GvwwefigwKlZB8B73hUaEOUHqjIn19huJpstaw0PH8OF4rpWTbl+ZSTKtdyYZOS6NfgcctyqYNCtYC7/qkBah5jJDx1KEho2pDJthsMF9CxL/bckTm7Giy2W4ehAoeaeDtzTXKBuyv+CfH55XCE8Y/wyO4srXa7Ntefhqm5a4gmJ4A5CDF9UrjRickxPisJxCoRhl8Rm04IGvdEe1A4/dwkLIXodcMXPWSMY/hWfepFZ5Epm2w0I8pWOu0TwIuRrxEedBNM1aRmWa6iHFq8HJULmHrW3Sma6sCpi52GGxcrUbWF78kVS5Lv7K7LgkbWCDvFguIs7d0rc03DZkCBWl1J1e+RSNtaiiT6VNh+R8TDxUUQg5ke7SsUqDs6nZ5efewL+liFeg9k+j0GE4C5sg/oy+KRXGRhk8Yx2Q/SnIa3iKmBvrLPNQ7uzmcycCtT2kfwZ4D+6/7wpPKWiUqHlfPQP+TewepvMU/PQi1nMG6FrIE9L4B9Dh6nyzVT3Eag/mvwbhSTeQgLU5m1VJ4Pvrx4fNNsB1NzwWDtnnqkAQnwcXg9UGKA26qzwI=
env:
  global:
  - secure: "TIrsA3R9MUJQ45q90Waq7CgExFXmM+3yXdHtA7l3UzAW1gPikmyDhIEIjQ8/XFLstpADcN2yc9iJjoyjtWt0P0DeHEbSOyvnjKYNLxnzdwBLxHy3qDhccBwUIHXYYybPwgSVBePlkiaD1QO9TpfuujOvCNHTP8Cjqm0XpQQQ6jmF9W5n2QJlZTWFfbPW1jLKe619BOY8s2xtkQOgIyE7p/2Yabe1p8cK70wKiz3lWwANkDelxg86QiXQbSpdwGFy1N1Mqj5cCzRu50gb31VAhswynPqtIxabWfJSHhuv0lf+ZmfVSqXtUNHflW3ZQBbkdVpF3Hxj5MKD61GrQgkR+n8lLv9YozgjJg67g1qKlrql1lsZW3daAVDeKlNUJZuWWCobPckNae0oW7YGf0AXzGDdQtDvXHECqVt5L4bncFyseINRjQNqe/Dqcyl/y1UtfSIZ4RVYGrBj460bKW2rYyvaUQnKTnek+1zCfyAngBAaJMk75OOMCb6+BzbWvM90jtbptsNJzjbg4efgyh/+5VzYT43S5TIIOKevb5M/cOHCEzqu1xS+xNun6/DjiycXCfgL7iFGG+MrHaYfUvv6u8qW87BcIoldvk+rRPNa6V6qFmEhbKlLN5LarGgc3y0RcV4qYDbnABgbbHdjkr1p4rhgBJzsWT7quMEWMITG1qo="
  - secure: "qATaqPuJ77YaAQPn0rDF6QWw+cgIXPiXK2Y6MO7affRgAXv4gONxLwaIOPiCMnJ3VSTU+RVPdoxpnHwS+F3uehbplMMlAJRsiwHNkLO6IiSXbTnyNjxIzPrqZ6KO3eRnHkN1grgQdBFa4Noss6xqbJZt4Bb86AbuErjlNp8xZpI3VOCaxRQP6Efwb9qCvZiklXAAn1LzWJ2NoqHLmoClUpa2gsseGCt2NDqMMy+VpkucxxNt/sgft3un2GSZaGj/qTd7ZVuem9PqxDaexie2xCyFegdTKC7kUu/Y6BvpRdiT/gSSIrv0WtrNVhMpsVOtR9mzKNL2vG93FSygFCZnmSP5qmzfVY1rVsIdPMrQi6xdergLxOZar9SexGUK1LsF4/434jbon2Zn0Debux20bgLCNf22TbPN4ZTs44abWBkS9E65supIT/gvzbp6BFf27Cmx0bDGkkL+Z4pniaSF3pZqYCnFtYwTQ5NbHYMKWgyUmkLc80rkrR7NW2/OSVjl4tos1oPdeUrHilgByf9wILmI19F2H8LMMO48MBViDSF5dKP1eXDYPh3JuziQTvEf5RsjshVMtwr+eCHs4RHFXjkn4tSh2csci/cOG4jObr6Cb/0RNcYOQ5mMNdQ+1MwrWa7mzkmO/Oh633rP2NalNPNkhY6GU0+ZjHdFukmQNHg="

