dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: "jhRukvjk6AdLV4vHnwgieHpjuH6gtaUgMClFdHZBG0P9PWZpmVpccEZI8dFZuo3/p32dC2N9qNe3dpijiRqX9k5ScUY2mdAnKVAyty12n/FXGs9qifGZUQKEUFzFWKSsTZcs3f1fDj4xCWiIc4OiYYnWObN4r1ZCybejqZ9N1AvfzNhAcx2IYBGyCqjJWAiP5UlusWiyK0Yst962HOqOKeoyM14doLeY/8D/1aPAKGqrQPM6gw3TwL/bdqmTzkLElKWAI6NHX3B2MJUlU+GsL3OGX3cSsW45LlVXvrFmh5IAqDvgRL6nKF/zMem3wGUruLAZ+eR1LwgfwwpRdVZn2ZpX542pyHGqXfQmbXJjzVXyZUdLmdTS4UxnBVi1V92AjWyMjZkJ1pl4DOj6TBkuxOe4DaMyfBSJGn5G0ZGck+xRiBrmOl5MQuo+MVu89bd/FKN0Ts5WxqVw3okCrjLs3wD24hGUA7qRLy5mXQxakFAx8D/EKQzecU4OrIubQ+u0LQxBLjOvC2zTbmjLrCZ81UfidymrN0UByvWFv02w4w7nHe88JmvACdHVFMk5SQXgqorAzgFk2dKCyvwYkK7epfDo8WQN0wsTa4E0evIbd+qhGgROwxq3LZ1tmO4q6iiRkvT0Gt1v/1rk/N99HjfVQkYl5XHJMlAtlDMOzsOfCDU="
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    secure: RcwiuQ/avAXchkwkFRSpjqw7QS68iXpP2cxLNul7pEEH2V4jqGgnonjRGANBqwqQfOibXdoZRsXQvHzKEXNgAUzfB9YwSABhJpmZGwj4u/jtzkf4zQuBPR/upOYrDgQBgH0zFB2Haum/lh60QYRzJjA9YtwxpOHoRPKCoab/Qo+w4gaL4WauxiygltfIPhCfDhDNa8TMsufV43jYemI9Ah8YB1jaKBHhVCZdBdxvYHV/FlkZEk2DeDQ7NWlaZ1iQv7QVlQp8sN0n4+7M4igqYYZJJ8IBrRq0S+pTvsbGCWf0GCTCzuXrIKXF8T2VFEaX22cAKLQAOkNW+d64L7QAPJ+c1lQWufnSYgbiSfSS5X4fNLN8BwrWWEUqLslQmQo5sJBrAzTCR9EX0I+N/Y0m808effghWwIHrcD+RTwS9/tV8oa5vR5s49Psba8KFKe5o7e31NjCRCXJ5jB6hcU1nVxjVwIDXMME7x/HRXpUt4dy0pQQES8i4PjqzB5DH4+7IX9um5VQuVDqlOvIXthLUDRTNPBJjmovGuwvaKX+1RMViqlC+uATCVA/wr8fW6JPmz3zLl7ldpqnr5+0BrbAwTnaQiCMteQJ1v23dYMekM+kQBzwbS3TcDCTZk5tNf/UWCxOm3YFiX3ReP/0hvs/PSyp04rw3e82gS1+hfR+Reg=
env:
  global:
  - secure: LhzytCOYtJJ3SmMY7JBe0T1QMb9PKswxsUv2j9TgsisfIG7q0z9ohl+foTeGW0IXxYtYmEluBGp8fZD29GVAsUyONA52LgwiEcUebufs7hQTqPXjZc6qIeh9KddNBXJKbO82u4jTbw+w5pFa4CjJIEltPJ11zXBsvYRyQDtQ2ZccYuDTuHHrt/SJbDHY2r7NUDfgZ/6x1v4esk5+iNC1TdE6d09JtjG3EFkDYIrZLMjtFJn2Ts1K1qbQm22yPgljYT8/1GerL7dUgxE0TAahmjJZu8L+nazhmBzW949q6S7sH8Bz5Hos/93OSZpTylftPIwSu5DkVthZho6RWaIT2oniue0OOJfmnrXdCE8O9a1MkU5d6KCtiih2t285mDsH/Zi/MNfyg2rZYzipGBjd0+fJ67wxc9kGK/dxm0iXkzme6pJJZEg1RSzHGvh+OORkSjLvUONWyDrhGbbmFxI9N9SAbnWX2G8t8rCtQNQyNrbbMo1atbBmjLrDsWfk0+3WgSWwXvyvbyb7XDGDi+QeA9W+6kO1v9idFBD1aWeknDJv03CZk1CdhOjxObDmC6RbgH/cGcEKfxbu7xtGLf7tYV3E9kb1Qeapu3rCpVnFiA3WHG07/gvlBVHt6nZMJIiFSugIqSPiYzpBu389/D0anbkwfDJA/72Pol9v4nEO00w=
  - secure: aiGHVIhYO6UbKcSlXVeLyPsQhkj1MeL9u1bxnbukaf22xkqgpkeVmAiC633+CkBgqueBSLLZPVXmDKurt3/i/igUGch0y9eYThWFSKQTXA0Ih2cYGmcA3bM7itctZmYZQ8sUwy6uRWoseTTfdbSLYXZG38W3F0NjnMjNt8bzzIP7wqQ9v7d12kMdrRBw84ZAxdAujCfdUoEm/bFMQ/XedJBs+OoTJpgzAFuDAavmyI6he7Dn9AlsyeZW4mrm2hDhQxr+wwIS0dXtVUad4fiiZcdpeNNDAERLbZYg+kENZ5DvLSYDx81jkaPwahMqVfPUEUKm7UfPps0G9pFvVUFQkBgwvDJb00pZfcsiK9anyy7gd7JutR7NUYrWiINd9g/jkTaN7FBCU4APOE3Bi/ZH7vvLjCIy0IYZT3ieVgYo4j4xFtu49Lc9M5ZvRYY8HiY1lycnC1TShGaknhpcSCd0fq7T6Nv59TZROAkBI95zsYC1FgKe/GnIfQd2otiievPAsF3UN/c32/E8BEz6BxXsIjbVBez838Wb2KpxPrlklE4NBeKWzZ1ULiMC6AEw//dGwY6ByhEiTNL/HJtiR+NXaPXbr+WHigyrFQ9OPre3xJpAxVBSa1huQUd4yW5cVlcNuScXYQwYdBvbzLmDcq8awk9Hd5mFZLwGuoXowIAn3h4=
