dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: "cjscommonplatform"
    token:
      secure: "ROwxs0F6YONAvYAL13MLeaGIcZX+Y9rLECLObridthOdlp0dqCdNfBGb67ls1S6l0l6Ktnl8AuCrxGNk8sq7k2PPM1lbqpCN5MlYPQQeu9Ta2Pv4g8dL3LDfwKRlcVklGYt1gERgzZt0h88jccSrJLx4DZre+ZRnZ+CRETErQrLQbOpT5PEfl3bZjgMHE/uZ9HwsVjonoUXn42vvM+pz4R222KuyHuaHOkUzziVOF9TOwmtIjYOerBQwJs9PMH8FstRhx8FNdMBsJuwqFXRfYEn6DURtjXjJekoOpOzb/SpuoLFjPqls43Y4PxnakcL7nvZ9j86dq2ubBV9M0JI8GztnjHVDZLXpjvtqvaSVOy+BrW066fqVevAAuVV12lul/OPyZmq1mnNSOlaVgGZ6/o73s782/7P8wasMWOYmnU2aKsEr4AYTJVq90ChM2GzQ5Uh2OZlov397CfVVglpWIdqiznJgHdq3c7X32HnKzJhIT1SWo0q/PPqYoT2BlT9um6IpTeT17guqcaB7KwbKyHkX4S7zz7LRMyIorrfwhR87fXBXdWkFwczL9JNaMMGZUID0Nf4Ujjwa2V6UJ4EtjTlGjzD7rLLWkrReQQzlmiiHPCUKXJ05GNcbRa2WZFD8c5SNKAFcGa83cVXOIcJBTzxaPGMHYhf2q2VbbRb18V0="
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh -DexcludeGroupIds=uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
  - secure: bZxPHt9OgOy6L4whNAnNi9OfGu1+enEvHahvRIn+hPEyHS0WlDxDZFw6cjxW170EY42H9hhCd3tuBhAytmiKf3d4tOIG3RNFZNi/btywutKKE2/qJz+qxzs22upmbvFSpbVhUGoOJr0JLPSd8hFJ1rwYiBCAOLVzpm+TSmVoYiUfFFhkpzP17xtG9aJHOI2QSvNlHVIR9J2VDb+LZ3WBvSJVAue+Qk18QB5/bqZ33Jeg5ayw09aoLQfR2+NuND/usk9qZ+Mt4j97YSpVzBR/FQTjvMzXngeFr7/Fl0U50DcKiwBjlev87nAilE3eZTSkPntzsmeq9XV0VjMG7dyDvyotHZb62c9gu/G+KefRELnruxSfz6u4BWKr/+LkV1jUalPeGQh5MRmZkKfit3QCbjLMJkS9MORhIpWg1oDzcRWJwXg7oUNttMj/1/j1evGL26rxdUVKJmLVUNYrlU1Sh/08cmCnNfSyqT5clVmsZnwQuHbP6qJsS6ReL3URHoRmwm2aR9opl1dv3GJ1REYH6akcm/NiOB20BtBetUkDNGAUb17xtnwM2WpWkpg7fstI8Vf+MFMJc5Ksti6aWBRbADSnaF2sIqMFGOwrT54TQB310n/Lf2tcWZv2V84y18cpMJCXrWeKtbVxIdJSnlLgbNloBBx1q/KUn3F7SckDHUw=
env:
  global:
  - secure: 0Kso+d8cx4gGkIATsMJEL2KOR6W5llgPAoILsiJIkqWKh0YqnNNNAxL/d43mZQWOJEIcTG9VMfuPdiAtCsx+WLSJmnRfF634nFxrGwwb7wf6ZFKEfbmAhdKuEsTPHoeCpu2WZW25kOaoa5CQHdppjX3wx5mxRMvWsHtZJXukrBQxVO+Ll2U2Hn5eZgRJQ11LHLj0qjnkDfgng9ZG+O7LY7YRSYTeYvhb8FcPKp8bWwGElyIIHbDkfXuaCBmmSeCxFRKqJ/+CTNBdpYPpwydsfrSI8bFwMb1HqSwlOjekMylRRxZN+KPfACF2tJf0GqNftWifMpi8P6PqRSC7hYkuxuVmxww9hMu1v9wbaCJomfWPhvJfzIxwNfB7I83fVYtMYmiQIZvakg7Hn8eIa7wWtVioUHSIEu0/na4rdKOvQnp52R/OTHLiBKgabndeb+mizNuhi6YqPwXWv0JDlNpnzAW/Qus1TpOWgfXTv675H/9uKsOE3+9If8yntUbRQeNp1mfGWgLrKxtKFvNZHFA18Qfx3i6U7tPrtiOWPZIAmTHteXt0dWxsF3g13S25Hr6ZF3bdvDwGaMcI9kecrOmHSHwP3tHTNDrZkeiHQWugFaSmXvcS2QIVZ6GiPM9f5iDaP6pYPcB1sX0ddKXO8owreAztEUiatnZ8dM5bE9HMnJw=
  - secure: 2Oj41MjR3x8oRSE/cORqgBvKbh+KFO2PqJhqQ1EVdb0h8qOWe0AlbNYrRW/o20dvMD4W2ZdO8u+AHCFtggRsjzBtKYysdtiPe0fxs9NpL6N4yNDZMuMuQJZJy2HpXN2FZsEebPpI9BS5N8+XOKFhtrSCX8I9qLcX8xhVE6izoCigSNTRQStHO+IcWhS4cOW5UPBJ7oHUQ2hYEFQ5VD5QhsZk1PLOz6wn2jQtJsgUh5Y1ghevX+ZARISf4GXO60CjnFCajV/L1nZvLVA2DijB80Gw5Z/snlgbAXiUIpeLxLEtG2d40PjXiRJdz8njTBwJiCV5HHcFDBM3EQTJhRBg9g5dG2bqOnPSCImt5tZp8awAIbGI+X9NbJFqlFJIsS7EjzpVqvF3yibKR3KY9pGmVcVr//s/Jq0Ti+knymhZkQUZ2Yuwjtm3Wzlr/3Z22WwG6bgJW89EbS3yUYYMAh/EuNyd9Dnzx/QLYsPDgc9YdBKo8QQd9GjSw6M+mmbMAxwxnxCt5lBrBnhTid6Z+GlRU4+D247VJcPokADTIh0tx90KA+/qg+XgnTtwC6JshosRrfVavk50K+qi+8t8N6DKJC199qTVQtEzJt15MtlGfupZWuHXqfSMtO69dQz13VUV/8MQS2Z9dtBargZBnQ+ffqpn6/g55PBLk1kgSJYWsDM=
