dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: zR7+ATdPqxG/kGdyUOeNhmOhajfpSUC0cs0HNt5QvEilAmzufQI0VkwWzTfYTJNZZJ+4okxwGS2Nx5AbTmUN21E9PSCr44o1GoU3hDU3sfeYQUc65VSXZfSYCwqIULykhoyZm7FolLMUnsX1UEJ8h7WMHZZ8r8xCZIPdUaAkTSlu3A58PTJBZDAtcXBdjWTIrFhuKMczen7LvfvDTrS8GwHGRUG8mRPMEQaIjgql+46jCYrDHR2PHFovP2ntwYveWpaC7L02GRFbPPihyMCmiTSxnrka+6+buhjU85dx8SME0dknYy4TUmqZmlVZWMml9cOT9c09gpUU48uVDV/AVCCiTK2+SDoC8nl8ggmsqX5K08sbLbJThifb2HTsjvagXYMtuXgJbyFAGwczbB0zKOMTFZ0fMcZlU1P3u7H30oTFKYNJLBiU5cM5zuhdKerkYKnDu+OPLIByv+k3JisUZxz6veu+wJY8kUQFoU5NbgEI6zIavWASqnOO/Qu2be2BX0Z2VmlYbQD9ODqB0K4JCswL6o38O88WpUL3iKgLHyNHE26pf5u1K9I1Tv+SM0Q0S4r6Dfw/Ol/4JfcVp8H7WldGl5AoGFyMb0tLjOLMshpfV8AxH+5qJMMQlpR2y2wliJW9UU5t26UdH4c2IwJLDO4Pn5PpH4jSav16NHAQAuk=
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
- ln -sfT ${PWD}/target/travis-settings/mvnw mvnw
- ln -sft ${PWD} ${PWD}/target/travis-settings/.mvn
install: "${PWD}/target/travis-settings/java/install.sh"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
env:
  global:
  - secure: 1XHnk03lFqyWSNGzU0NkhU2DCYMJvF5RUtJ5sg63NpLhU30AwGHKKWwlt0tfaedxx7YYmLEv7iGoo9+P62P3ff988eGcrNXFkTiG9K/fgQXx6FgPve8oxzN7zMH1vnBAqZlMrvtX1KFfMWbBZRMUFUok+RymQObw1JyMRPMreeFRdp+tJfSPIJpiUNiIpFZdZK6/u77VKVj3gsnQ6smuuNXoObh1+V0ki2NFfOvtJLiIk9bn4rGqnWYhwXxYEVGdyWSup8b2DDRW4W48tkHlsV2FQkPOyxE5//xlvhwDccm7SRUBs1vYcNYyfGmbHPGz6435h5Q/nW7vC+jsykSOuxelWzX5Qu42dED8uQqe1Kdk4BcHPp+mQnQH5dgbXVEgQthYAURYswTOSkNpgYg6f5+jEeC8MbWIE10Xer3YDOL/JFmyQ3zRoXPAq/qunZHwZUAUjKBJdipTkz7KKfmZL6QAa8w6wMfPzXnR+MJs5oTHJhdSP9WWID5R7IvasH4WicnrIOA78AaIPBFVccye1BWl5/hSp1UWhzqFkgRhxKe0rJBGreWPJmh1jqPSEOGet7Qwf+86HAMb5pH50RkfsiUFDZP5Xi+hLU6wq9NyyPHhFEvWfDx9CWfbiYLTeA5iRMiItqslwMNZJmNjq31hLDBxsaSumlVAWN0oLmKQVag=
  - secure: iybg9Q5aaNvjbBrBmXfRLNX4Bfnn7ptNvM7rNXEqPRyHAWWO/rZe+E6Ud2/6w0Y+mzYSAETOCKxReTjN5jc2UjZw5l8H3LgFGbwJgIlS9fLnHLOkz+Si8OT93pH8N1GFeaKcgr4Ve0yC0cYjLPewK3aBQM+gpQzYxy1sux9wlBlDBwJdqkauP9jDrYGmHipqDPMBHfVwSezgb9CBHLce3OSMCQseMvU7oDXcdBpc7x/q2Jw/ozSDI2U9oUBvLHZ7GDr5UWlMMJBLIoea/wnK0zeMzYDJAlBsCufhZRWsdO6CM23xTC8XDd8z2IEd+wVMX0FuyT9eWUSIiUSRa1CasVWwtbG7mD7ohMzTYTQWPwJcQG4dL3XWG/WkCsi4v+XOKRMvIxO1/nd4pINbIZWeXNbHVAIaO+F8aWnqFQtxcFvYiCefVd2aMsddSSsBqkmVxQKJX3F7wJIZqVlx245bHy5yMoik8+yBOsA32Sw4m885qvaispPmIi6QOYaNY0Is6sKDJANgnjEPFNPOTN1mPEfLn1cVNaClki8jjaWrOVSJ0SZ8HmPXXP48dUsyhRwEKhBSXvT1GJ0ShmXX9nXw/P6leIpiKGo1u3A6eELd/N/szLN8b6L4meD7D4t2paphtr688bthVZG9VQSZZnZb+88xA/xiO2VO9sGyY0NIF2A=
