dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
addons:
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: FR2bQjMTlZRHuNr0jmtHENEMktK7m4ynWT6qiJRq9YBUjjkhf+5apzHvby628rYBDOPs/a74fznuUzotZmzXzdMJPH+1tHlvCsqyMgYsSpk5NzVt3YrJ0kmLlJGdNMgIk+R7SNQljjYVJ/6QnxyfueWn+KHQv7ddwEyz0NcWCh/YP19sUbSxH4V/0DrsqP4fmdXHfF9zV5HpxwEm3UENx251M0KWZyn6ZqdYXc3zy/lewLxd/FQsCVO8/6sqn8i3bqbEcaivTwL2e3uOyI6xcq9v7lvmO8TPSb7c1HD8T2rrpmnhX13APue7hNAXjDP0nyI4LK/LvfNoJdBCp2Ftchb6d+9CJCR+hf3ZwGP1JWyddCb8JbCFf5CTT4lLdQt0P7AG4jK8T+ilNPcy+GK1QixqAC2GVb73kYmCvB+O6gYcg2KkxShnXJlOY9ubCBjXuGZxL9afOVSfUCWICTc49rCLVFvcLNDcCIGPKKDF+CmKws5U+MatjzwJPtjD5MplbWpTJ6cqWkEvIleQIfQph50fR0lRD8Xo7IVeEvkk6wKrxn32hMsV03eyfEE+mF16gQSpUFDYnnEBnfcLqC3rSFZSZfab67nPF4s3B1CYR8KSGIleCqDwSnvosFxw6rTkWfyIyrzV3MCu6qTSIoX786h8tx9gdCF88gbW2sbgJmU=
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh -DexcludeGroupIds=uk.gov.justice.maven"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    secure: fPlaMvrczZ2riJ4tjMOAqxSGj4JfxGlH/K08knLgG4T/n6EL4LN4+184Npz9XueNbV3m26WUrPkbXEiWXpqkKsbwcZXqqnFxGacGiyxv7LeBeQLYp7NFeARAyB5qDwUpjHlCPAEoAeyeGsZNrpui/wceY4j1tB7ObfdwbxLzAO0tekdbwitSaK1cc7V2sVHkBYr7ChuC+dVO1pshPw0EVTmzPioS8nfFKPaxWoMgyRAuYe7MD0U7DxNQ4Wzsb7tpfd5Oom1wLXyZ7M3wwSMMamIAAxHVG389Az6YvN7hXQggTGDawf/YwVOaoMR2bh7uHBCOiNZO1GbRTOA7IuTPwT7GsK94THRtfvqNm7RFBPkoD4657FATnk2o5c7QNTY3dAlYLsxLnS6mVTL/vAbqC7BbDHo/UGsxmOusQtKt8sRoL8pOCEInHaS3b88Osl7u7oYO/E4YTptdnkEe8tNyWWdx34nEUT0j1Mu/VAN38YcgTMUuiBU6chkMJ5BjIHisJlAAnBJ9VGgF9liqnigNwAGhbrHZPyAlKUX8HLejpD+t4aR0UaEvvauh6aHh4pYm0mZra4zOBC/lBDOXqsu5ajHL8LpHc6j+5FrmNwciiTVoxdud2S4c0U2ymr3L07ivX+UyhoraS9oSH3v7L73Q4NyvuAmD8Zc0xw/cR4Pff9c=
env:
  global:
  - secure: bCA/7wvRKCMWFcgYE7842kyRClFlOO6ABFl/Sdc35/JQSr1fuse5WnsSVEpP6zmW3q1crsC2tSoKPwDRCU5B1LV1Ehuj+sWYKy7uCExUIJ09gGKzAv6T2s22ngBGy0S3EwqUcZO8/qX3iu0DUyGb8A+xWOSiKvV+H39nZ5QcEZUe8vH1sDX/OeCY08Z7wS++wivwz/G1guS8uov2Iqi3ql6cTdCFlGR3Bw1pbHr4RBeKaPidB8jh3Jvyk6EOWIP5LhJcdBZfl/pcixEtIuRtyyyqjNwqFwtGk7ec0nU7v2ZjYtJOnN3jSkoGJmCG20KYpqbaDzrPbE6G4NxkyBS765fKtGilw6LqOhb1YMdEQyF6MdIAj2dPvs4ehAc0v1ycDl6ihSRI19rjhDJzp83osHm8AWX+8g3yk9Eblwd9nNEIMPhmHcfJ2kBjELmPWXVOBEw2xafsTQk5ftpYhu+aoLpT0SLIwFp3pzfHyF0u4u73wiPRiXpuJ2+44YA/w0eQlGj6VKP4UULspZmI4rmWZw9Nc+EncMa6ZhTM8c9Njkk5s6hDrpmFK9ufvqe+3PkyUdjkHR7+76iM5XY/NR/nacm4oBnR38czvA4GjM6Y/l/xOOdoo5ZtKzwbiP3k0+JoKwG0mwzV2E6iIASB1G4Wc5cenhW2QDmiSeTjzKN/784=
  - secure: PuLUOFGbwhCveBo6t6p6y4i9yzHMjg/M9y1W0VWQrT4oJC8UpOiAub+/gmrwhC3/Bp/JgdwxHdB3iDQ7JTcIya3pLJsV5/2dgA/pa7LiwihZDQubFlQHeu6QZqth0zdkU7TNjb0litTFADaUDoorLRqAS8LUio+3y+V2oLNXHxT9jg5wtxOr8Q3oM5AItDOAz64gx+G52umpvKQrSikHn4HwBnBHLfLQ83UygdNM0DZZDr+KUMzxSWx9A9FW2D1FTZ9hKx6AchuyHPlN4gwlfptylzJ0ilLnftiLP1hVS6wm6DnhMRQO9QhG2cHt9W5yEDX0qiWT/IRnApB1yIUsqqEQfGt2Pv7qoPURGltAND0UX5+tLrSqcgJBKv0ZRYYBjzy/BwIj8B6Cao6F0r1mWyBChRT3OHZ7I9hpH//U7Qqp2EwC5kbhFEgzlwia1mkH9Yd7BlH3otyM854p8eOFQY8yARJDWrhjoJ4wPDBcTKj2N6CUZ8JSDPlsaqUAX8UTgazpxEkDehKqjFdwVtUXFtKSLDLPBJHzerYxwLwz9fEIdKS52+iRcLkFysTUJXa2FnUacWibWB1ilo5z1ZZK7bzzYwF7rUF6UauW0P3n/oLDRhOS9QySeeSpzdJ4T+1Tl5T1QLTQo1HEsYnwuI18bkW3Mrw8JIUvCDFMcK92s/s=
