dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
install: "${PWD}/target/travis-settings/java/install.sh -DexcludeGroupIds=uk.gov.justice.artemis"
script: "${PWD}/target/travis-settings/java/script.sh"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    secure: RhBrMzy/IkACEbuqk7EoqYeq8XKfG75LPweYJ2V/+czhn8GlBzCMcV05aYAQ1917T+SVSTco8Zs5De1yO2qAq+jiTp9ehepoarAu064tX+lQBMWBq8SYfvdYVCJTAvQ/QceAVcIyYZ2xL23H5nbMJgu2NXn5uKsslDlNH03LBibYTMN57sWN74gpya4895Xy1CP2QJfKkP3AQuzO2dl7kHBS+ZKUlIc10KpNbPlIr/2OPJgT6EyhXjugzw9U6GZv06U6JjdrFQyJFjUyfADv77fC3gKmsz9THJBUj4YKzD1rXQXsfvi4KFTTWFa3W8rjDpaQoZfFvzZ8wDqd/sZdWJ/AGm0JBzLsmAy4Mlj9+ArDDpcME56a4KKPFfyYlk88Ni/PQqQmpsY+N6EaMJ+DjTsmLynGZIx5Ne9As9zkQvfZg/JCpBlFaFL61ZIiMMFfLoqo3wd8C7Sh10ZO5Fl7URlMMyZAKMKwowwrQc93FUDs5xOqeZWO019y/DslzwO0oDan+9nLwqnZ1Ca7Wjjg0ODMyFzQCj/IT0j55x3FSdeUBfHAJ2mshTiaKtfWqEK9K9wuUJjLNpAG1s5dTboWx41ReaU5/eYcURXHVlpTNypyPSopxhRK+TVIQQgfqgImclpq2FFwdpD/CQb6PfXONFPEeeNuCI5UBMAz6K9S91U=
env:
  global:
  - secure: XIjTSjKsPAQdyBfv6jnnIRATMDA4FG5XD9cksYO8W9dkGHrC9wdQrUlnshpR0wuz6Ap5tCCv0ZAJ8hDNZfS12JqT9zFiX91dRU+v3J7M6SaH9mojHG0vFQ4+objM/ni3RIhojie9FtfJCXwtgP/TZknswpb3cOeRBTqrlCxQJ5LEjEt433swG49NQ5RGMPqnIyVOOOIazSxxpXGYMbEunAIPAh4smxjDWzyHyjsOMCxFhamcYDOz4B4FrTiSYyj6OXQoaphonvLNVTVD+4ZYBXmD6j2PIJ2Z7mLo3NvcKjSC5yiVUOy+2dDoHt8PveTVr85hNYaZHCpnH9JOzSuruF3CCoL0pcQ69wapUjyZBttvZIQRZb2MTbEZ0TqHrVzw+zBrZFpkfUWooEbmC7UWYGQzBf5wdprgltCsD7ldEt6JMW1G2R3/UCPpLcnpkcxDrs0GgWPNWGQsgOIJV5XLq/lmBugvC04SnS3RIm/h0nAgkErOjr5lbOZituqGN06sJFVB63YreWYmVGlai7+4zp+JHWQ0aFQ0mkfhVGbEs/x5nA+YfcrDTJmXtmv1BBbQigE2OefYyZt3IgIxHnhaEp4QLEs9GNKfaHnHjPoFjc5fHZNtWuDgIRYIjUu+d86Ugb3TkxyOQs8SyeeIl7C6HLiJMc84p4TSFSYYt5lHUfE=
  - secure: j17ntdUpUgtqg0RkX5ur/KHzs14lk5lXwpOxHDQZYj60jSdd1+gzKAOepu8A1NX/x9F7R7nxAY4dNf/prK1ZymjBiMisyHHhIiRC9i3+/0VxR8p+WGGcUaWo25/i9XomJgdpSJQGOyVXb4kPbW3iWspjk4axHQuJjBtFFsXDum7qN3iFxj+e8ETP18udwOBq+9/Nu8jLt/n2RK/MfYt3h397L1e7i8hD2eX7Bh71ymVythfEOidoO5o2SbgxLh2+cFYUOOpnm58kAoGAuAOHuHU8gfM0hrVPgrEZXg3jgJeywaoM2o2nIE3OIdqhDuIB4SqCQhFZqyGOYQfmAYyFMCtManZLxX7z2CddtD1Eri8Z/D2vMxJOaOPVXcwFuAa13Ulk29w9LNa4EKcaFRU/qpbVv6wXLy4DZoJiPRYB0PmPYQ090otvvX9OtrsNF5I2O9JIlwXq0pnOczxKRJ1cXaSEnqx+NB86WGz9Q70rmMUADdkeHVle+iDk7LJ9Fw+MEgh+QpV2xlXig9pBqNny6KArjzAGFdkrdgR733uVWAtJp0lDn/6QfuzPsJUTjM+p1OCldROU8NqDOlMcxScAvgFzJCa0huLPI5lmD1qa1tfqx5oQHYhXcwSQvcLpYeIoM2glgdcR4EY6QkWFzXRnQUsOz6IRC4GPuLH+zvuo19A=
