#%RAML 0.8
title: Cakeshop Command API
baseUri: http://localhost:8080/file-alfresco-example/command
version: v0.1
mediaType: application/json
protocols: [ HTTP, HTTPS ]

/files:
  post:
    description: |
        ...
        (mapping):
            requestType: application/vnd.example.add-file+json
            name: example.add-file
        ...

    body:

        application/vnd.example.add-file+json:
            schema: !include json/schema/example.add-file.json
            example: !include json/example.add-file.json
